SystemOrganization addCategory: #'Walrus-Metadata'!
SystemOrganization addCategory: 'Walrus-Metadata-Annotation'!
SystemOrganization addCategory: 'Walrus-Metadata-Loader'!
SystemOrganization addCategory: 'Walrus-Metadata-Metadata'!
SystemOrganization addCategory: 'Walrus-Metadata-ObjectReference'!
SystemOrganization addCategory: 'Walrus-Metadata-Util'!
SystemOrganization addCategory: 'Walrus-Metadata-Visitor'!
